[0m14:15:36.212999 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000018A2F060400>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000018A30F3BB50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000018A30F3BE50>]}


============================== 14:15:36.217114 | da9ccfb6-1fcc-4950-8891-bae199f28b54 ==============================
[0m14:15:36.217114 [info ] [MainThread]: Running with dbt=1.9.2
[0m14:15:36.218193 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\hangu\\.dbt', 'debug': 'False', 'warn_error': 'None', 'log_path': 'logs', 'version_check': 'True', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_format': 'default', 'invocation_command': 'dbt init project_dbt', 'static_parser': 'True', 'introspect': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m14:15:36.253465 [debug] [MainThread]: Starter project path: D:\traning_DE\project_training\Code_Dbt_OD_Minio_6_2_2025\dbt-env\lib\site-packages\dbt\include\starter_project
[0m14:15:36.315356 [info ] [MainThread]: 
Your new dbt project "project_dbt" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m14:15:36.316356 [info ] [MainThread]: Setting up your profile.
[0m14:15:36.317357 [error] [MainThread]: Encountered an error:
'charmap' codec can't decode byte 0x90 in position 19: character maps to <undefined>
[0m14:15:36.420918 [error] [MainThread]: Traceback (most recent call last):
  File "D:\traning_DE\project_training\Code_Dbt_OD_Minio_6_2_2025\dbt-env\lib\site-packages\dbt\cli\requires.py", line 153, in wrapper
    result, success = func(*args, **kwargs)
  File "D:\traning_DE\project_training\Code_Dbt_OD_Minio_6_2_2025\dbt-env\lib\site-packages\dbt\cli\requires.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "D:\traning_DE\project_training\Code_Dbt_OD_Minio_6_2_2025\dbt-env\lib\site-packages\dbt\cli\main.py", line 477, in init
    results = task.run()
  File "D:\traning_DE\project_training\Code_Dbt_OD_Minio_6_2_2025\dbt-env\lib\site-packages\dbt\task\init.py", line 346, in run
    self.setup_profile(profile_name)
  File "D:\traning_DE\project_training\Code_Dbt_OD_Minio_6_2_2025\dbt-env\lib\site-packages\dbt\task\init.py", line 248, in setup_profile
    if not self.check_if_can_write_profile(profile_name=profile_name):
  File "D:\traning_DE\project_training\Code_Dbt_OD_Minio_6_2_2025\dbt-env\lib\site-packages\dbt\task\init.py", line 209, in check_if_can_write_profile
    profiles = yaml.safe_load(f) or {}
  File "D:\traning_DE\project_training\Code_Dbt_OD_Minio_6_2_2025\dbt-env\lib\site-packages\yaml\__init__.py", line 125, in safe_load
    return load(stream, SafeLoader)
  File "D:\traning_DE\project_training\Code_Dbt_OD_Minio_6_2_2025\dbt-env\lib\site-packages\yaml\__init__.py", line 79, in load
    loader = Loader(stream)
  File "D:\traning_DE\project_training\Code_Dbt_OD_Minio_6_2_2025\dbt-env\lib\site-packages\yaml\loader.py", line 34, in __init__
    Reader.__init__(self, stream)
  File "D:\traning_DE\project_training\Code_Dbt_OD_Minio_6_2_2025\dbt-env\lib\site-packages\yaml\reader.py", line 85, in __init__
    self.determine_encoding()
  File "D:\traning_DE\project_training\Code_Dbt_OD_Minio_6_2_2025\dbt-env\lib\site-packages\yaml\reader.py", line 124, in determine_encoding
    self.update_raw()
  File "D:\traning_DE\project_training\Code_Dbt_OD_Minio_6_2_2025\dbt-env\lib\site-packages\yaml\reader.py", line 178, in update_raw
    data = self.stream.read(size)
  File "C:\Users\hangu\AppData\Local\Programs\Python\Python310\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 19: character maps to <undefined>

[0m14:15:36.422917 [debug] [MainThread]: Command `dbt init` failed at 14:15:36.422917 after 0.35 seconds
[0m14:15:36.422917 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000018A2F060400>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000018A30F3D360>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000018A30F3D510>]}
[0m14:15:36.423925 [debug] [MainThread]: Flushing usage events
[0m14:15:37.629087 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m16:30:36.311514 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000016BF8A44400>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000016BFA91FB50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000016BFA91FF10>]}


============================== 16:30:36.317577 | fe43dc34-1127-406f-8c06-9e30d24ec8d9 ==============================
[0m16:30:36.317577 [info ] [MainThread]: Running with dbt=1.9.2
[0m16:30:36.318593 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'fail_fast': 'False', 'log_path': 'logs', 'version_check': 'True', 'profiles_dir': '.', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'invocation_command': 'dbt run --profiles-dir .', 'log_format': 'default', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m16:30:36.318593 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path D:\traning_DE\project_training\Code_Dbt_OD_Minio_6_2_2025\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m16:30:36.320645 [debug] [MainThread]: Command `dbt run` failed at 16:30:36.320645 after 0.12 seconds
[0m16:30:36.320645 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000016BF8A44400>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000016BFA91FA90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000016BFA91F970>]}
[0m16:30:36.321643 [debug] [MainThread]: Flushing usage events
[0m16:30:37.516457 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m17:00:45.611153 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000014454F04310>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000014456DDC880>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000014456DDC550>]}


============================== 17:00:45.621162 | 12ef39b1-129d-4277-bc4e-a970ec54a472 ==============================
[0m17:00:45.621162 [info ] [MainThread]: Running with dbt=1.9.2
[0m17:00:45.622164 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'version_check': 'True', 'log_path': 'logs', 'profiles_dir': '.', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'static_parser': 'True', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'invocation_command': 'dbt run --profiles-dir . --project-dir . -s models/example/*', 'send_anonymous_usage_stats': 'True'}
[0m17:00:45.623160 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path .\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m17:00:45.624160 [debug] [MainThread]: Command `dbt run` failed at 17:00:45.624160 after 0.15 seconds
[0m17:00:45.625163 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000014454F04310>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000014456DDC4F0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000014456DDC550>]}
[0m17:00:45.625163 [debug] [MainThread]: Flushing usage events
[0m17:00:46.910701 [debug] [MainThread]: An error was encountered while trying to flush usage events
